# Generated by Django 5.1.7 on 2025-03-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
