# Generated by Django 5.1.7 on 2025-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_completed_alter_purchaseorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
